const programmingJokes = [
  "Why do programmers prefer dark mode? Because light attracts bugs!",
  "Why did the web developer walk out of therapy? The therapist kept telling them to break their problems into smaller divs!",
  "Why do programmers prefer iOS development over Android development? Because on iOS, there are no Java exceptions!",
  "Why did the JavaScript developer break up with their React partner? They had too many dependencies!",
  "Why do web developers prefer to work alone? Because they don't like merge conflicts!",
  "What do you call a programmer from Finland? Nerdic!",
  "Why do programmers prefer cooking? Because it has great recursion!",
  "Why did the web developer always go broke? Because they spent all their dough on cookies!",
  "Why don't programmers like nature? It has too many bugs!",
  "Why did the web developer go broke? They lost their domain in a bet!",
  "Why do programmers prefer iOS development? Because the Apple doesn't fall far from the tree!",
  "Why was the web developer fired from their job? They couldn't control their URLs!",
  "Why did the developer go broke? They lost their cache!",
  "Why did the JavaScript developer go broke? Because they lost their prototype!",
  "Why do web developers prefer the desert? It has great sand-boxing!",
  "Why don't programmers like insects? They prefer bugs in the code!",
  "Why did the web developer refuse to play cards? They didn't know how to handle shuffling!",
  "Why do programmers hate nature? It has too many bugs!",
  "Why did the web developer go broke? They couldn't make enough JavaScript!",
  "Why don't programmers like nature? It doesn't have Wi-Fi!",
  "Why did the web developer get locked out of their house? They forgot their keys on the keyboard!",
  "Why don't web developers get invited to parties? They always break the link!",
  "Why do web developers prefer tea over coffee? Because it's easier to JavaScript!",
  "Why did the web developer become a musician? They wanted to compose web symphonies!",
  "Why don't programmers like to exercise? They prefer software curls!",
  "Why did the web developer always carry a pencil and paper? They liked sketching websites!",
  "Why do programmers prefer dark chocolate? Because it's object-oriented!",
  "Why did the web developer go broke? They lost their cache!",
  "Why did the web developer become a gardener? They wanted to work with root vegetables!",
  "Why don't programmers like HTML? It has too many tags!",
  "Why did the JavaScript developer go broke? Because they lost all their prototypes!",
  "Why don't web developers like to play hide-and-seek? Because they prefer finding elements by class name!",
  "Why did the developer go broke? Their code didn't have enough inheritance!",
  "Why don't programmers like the outdoors? It has too many bugs!",
  "Why did the web developer go broke? They spent all their money on domain names!",
  "Why did the JavaScript developer go broke? Because they lost their scope!",
  "Why don't web developers like to go shopping? They prefer online carts!",
  "Why did the developer get kicked out of school? They couldn't solve their class problems!",
  "Why do programmers prefer seafood? Because they like to catch shell bugs!",
  "Why did the web developer become a detective? They wanted to uncover hidden CSS!",
  "Why don't programmers like to take breaks? They don't want to end up in an infinite loop!",
  "Why did the web developer start a band? They wanted to code in C Major!",
  "Why did the web developer bring a ladder to the bar? They heard the drinks were on the house!",
  "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25!",
  "Why did the JavaScript developer go broke? They lost all their inheritance!",
  "Why don't web developers need umbrellas? They prefer to use cloud services!",
  "Why did the developer go broke? They didn't get enough interfaces!",
  "Why don't programmers like to play hide-and-seek? Because they prefer to use display: none!",
  "Why did the web developer become a zookeeper? They wanted to work with web spiders!",
  "Why don't programmers like to eat alone? Because they prefer to dine in groups of bytes!",
  "Why did the developer go broke? They lost their keys!",
  "Why don't programmers like shopping malls? They prefer the online shopping cart!",
  "Why did the web developer go broke? They spent all their money on hosting fees!",
  "Why don't web developers like cupcakes? They prefer cookies!",
  "Why did the developer become a beekeeper? They wanted to use a lot of buzzwords!",
  "Why do programmers prefer the beach? It has great CSS!",
  "Why did the web developer go broke? They lost their domain name in a bet!",
  "Why don't programmers like analog clocks? They prefer digital interfaces!",
  "Why did the developer go broke? They didn't get enough classes!",
  "Why don't web developers like to play cards? They always get confused between clubs and clubs!",
  "Why did the JavaScript developer go broke? They lost their closure!",
  "Why don't programmers like going outside? The WiFi signal is too weak!",
  "Why did the web developer go broke? They couldn't make enough cents!",
  "Why did the developer get kicked out of school? They couldn't solve their class problems!",
  "Why do programmers prefer dark chocolate? Because it's semisweet!",
  "Why did the web developer become a gardener? They wanted to work with root elements!",
  "Why don't web developers like to go shopping? They prefer online stores!",
  "Why did the developer go broke? They lost their keys!",
  "Why don't programmers like to go fishing? They don't like to catch bugs!",
  "Why did the web developer become a detective? They wanted to uncover hidden bugs!",
  "Why don't programmers like to eat alone? They prefer to dine in groups of bytes!",
  "Why did the developer go broke? They didn't get enough interfaces!",
  "Why don't web developers like cupcakes? They prefer cookies!",
  "Why did the developer become a beekeeper? They wanted to use a lot of buzzwords!",
  "Why do programmers prefer the beach? It has great CSS!",
  "Why did the web developer go broke? They lost their domain name in a bet!",
  "Why don't programmers like analog clocks? They prefer digital interfaces!",
  "Why did the developer go broke? They didn't get enough classes!",
  "Why don't web developers like to play cards? They always get confused between clubs and clubs!",
  "Why did the JavaScript developer go broke? They lost their closure!",
  "Why don't programmers like going outside? The WiFi signal is too weak!",
  "Why did the web developer go broke? They couldn't make enough cents!",
  "Why do programmers prefer the desert? It has great sand-boxing!",
  "Why did the web developer refuse to play cards? They didn't know how to handle shuffling!",
  "Why don't web developers get invited toparties? They always break the link!",
  "Why do web developers prefer tea over coffee? Because it's easier to JavaScript!",
  "Why did the web developer become a musician? They wanted to compose web symphonies!",
  "Why don't programmers like to exercise? They prefer software curls!",
  "Why did the web developer always carry a pencil and paper? They liked sketching websites!",
  "Why do programmers prefer dark chocolate? Because it's object-oriented!",
  "Why did the web developer go broke? They lost their cache!",
  "Why did the web developer become a gardener? They wanted to work with root vegetables!",
  "Why don't programmers like HTML? It has too many tags!",
  "Why did the JavaScript developer go broke? Because they lost all their prototypes!",
  "Why don't web developers like to play hide-and-seek? Because they prefer finding elements by class name!",
  "Why did the developer go broke? Their code didn't have enough inheritance!",
  "Why don't programmers like the outdoors? It has too many bugs!",
  "Why did the web developer go broke? They spent all their money on domain names!",
  "Why did the JavaScript developer go broke? Because they lost their scope!",
  "Why don't web developers like to go shopping? They prefer online carts!",
  "Why did the developer get kicked out of school? They couldn't solve their class problems!",
  "Why do programmers prefer seafood? Because they like to catch shell bugs!",
  "Why did the web developer become a detective? They wanted to uncover hidden CSS!",
  "Why don't programmers like to take breaks? They don't want to end up in an infinite loop!",
  "Why did the web developer start a band? They wanted to code in C Major!",
  "Why did the web developer bring a ladder to the bar? They heard the drinks were on the house!",
  "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25!",
  "Why did the JavaScript developer go broke? They lost all their inheritance!",
  "Why don't web developers need umbrellas? They prefer to use cloud services!",
  "Why did the developer go broke? They didn't get enough interfaces!",
  "Why don't programmers like to play hide-and-seek? Because they prefer to use display: none!",
  "Why did the web developer become a zookeeper? They wanted to work with web spiders!",
  "Why don't programmers like to eat alone? Because they prefer to dine in groups of bytes!",
  "Why did the developer go broke? They lost their keys!",
  "Why don't programmers like shopping malls? They prefer the online shopping cart!",
  "Why did the web developer go broke? They spent all their money on hosting fees!",
  "Why don't web developers like cupcakes? They prefer cookies!",
  "Why did the developer become a beekeeper? They wanted to use a lot of buzzwords!",
  "Why do programmers prefer the beach? It has great CSS!",
  "Why did the web developer go broke? They lost their domain name in a bet!",
  "Why don't programmers like analog clocks? They prefer digital interfaces!",
  "Why did the developer go broke? They didn't get enough classes!",
  "Why don't web developers like to play cards? They always get confused between clubs and clubs!",
  "Why did the JavaScript developer go broke? They lost their closure!",
  "Why don't programmers like going outside? The WiFi signal is too weak!",
  "Why did the web developer go broke? They couldn't make enough cents!",
  "Why did the developer get kicked out of school? They couldn't solve their class problems!",
  "Why do programmers prefer dark chocolate? Because it's semisweet!",
  "Why did the web developer become a gardener? They wanted to work with root elements!",
  "Why don't web developers like to go shopping? They prefer online stores!",
  "Why did the developer go broke? They lost their keys!",
  "Why don't programmers like to go fishing? They don't like to catch bugs!",
  "Why did the web developer become a detective? They wanted to uncover hidden bugs!",
  "Why don't programmers like to eat alone? They prefer to dine in groups of bytes!",
  "Why did the developer go broke? They didn't get enough interfaces!",
  "Why don't web developers like cupcakes? They prefer cookies!",
  "Why did the developer become a beekeeper? They wanted to use a lot of buzzwords!",
  "Why do programmers prefer the beach? It has great CSS!",
  "Why did the web developer go broke? They lost their domain name in a bet!",
  "Why don't programmers like analog clocks? They prefer digital interfaces!",
  "Why did the developer go broke? They didn't get enough classes!",
  "Why don't web developers like to play cards? They always get confused between clubs and clubs!",
  "Why did the JavaScript developer go broke? They lost their closure!",
  "Why don't programmers like going outside? The WiFi signal is too weak!",
  "Why did the web developer go broke? They couldn't make enough cents!",
  "Why do programmers prefer the desert? It has great sand-boxing!",
  "Why did the web developer refuse to play cards? They didn't know how to handle shuffling!",
  "Why don't web developers get invited to parties? They always break the link!",
  "Why do web developers prefer tea over coffee? Because it's easier to JavaScript!",
  "Why did the web developer become a musician? They wanted to compose web symphonies!",
  "Why don't programmers like to exercise? They prefer software curls!",
  "Why did the web developer always carry a pencil and paper? They liked sketching websites!",
  "Why do programmers prefer dark chocolate? Because it's object-oriented!",
  "Why did the web developer go broke? They lost their cache!",
  "Why did the web developer become a gardener? They wanted to work with root vegetables!",
  "Why don't programmers like HTML? It has too many tags!",
  "Why did the JavaScript developer go broke? Because they lost all their prototypes!",
  "Why don't web developers like to play hide-and-seek? Because they prefer finding elements by class name!",
  "Why did the developer go broke? Their code didn't have enough inheritance!",
  "Why don't programmers like the outdoors? It has too many bugs!",
  "Why did the web developer go broke? They spent all their money on domain names!",
  "Why did the JavaScript developer go broke? Because they lost their scope!",
  "Why don't web developers like to go shopping? They prefer online carts!",
  "Why did the developer get kicked out of school? They couldn't solve their class problems!",
  "Why do programmers prefer seafood? Because they like to catch shell bugs!",
  "Why did the web developer become a detective? They wanted to uncover hidden CSS!",
  "Why don't programmers like to take breaks? They don't want to end up in an infinite loop!",
  "Why did the web developer start a band? They wanted to code in C Major!",
  "Why did the web developer bring a ladder to the bar? They heard the drinks were on the house!",
  "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25!",
  "Why did the JavaScript developer go broke? They lost all their inheritance!",
  "Why don't web developers need umbrellas? They prefer to use cloud services!",
  "Why did the developer go broke? They didn't get enough interfaces!",
  "Why don't programmers like to play hide-and-seek? Because they prefer to use display: none!",
  "Why did the web developer become a zookeeper? They wanted to work with web spiders!",
  "Why don't programmers like to eat alone? Because they prefer to dine in groups of bytes!",
  "Why did the developer go broke? They lost their keys!",
  "Why don't programmers like shopping malls? They prefer the online shopping cart!",
  "Why did the web developer go broke? They spent all their money on hosting fees!",
  "Why don't web developers like cupcakes? They prefer cookies!",
  "Why did the developer become a beekeeper? They wanted to use a lot of buzzwords!",
  "Why do programmers prefer the beach? It has great CSS!",
  "Why did the web developer go broke? They lost their domain name in a bet!",
  "Why don't programmers like analog clocks? They prefer digital interfaces!",
  "Why did the developer go broke? They didn't get enough classes!",
  "Why don't web developers like to play cards? They always get confused between clubs and clubs!",
  "Why did the JavaScript developer go broke? They lost their closure!",
  "Why don't programmers like going outside? The WiFi signal is too weak!",
  "Why did the web developer go broke? They couldn't make enough cents!",
  "Why did the developer get kicked out of school? They couldn't solve their class problems!",
  "Why do programmers prefer dark chocolate? Because it's semisweet!",
  "Why did the web developer become a gardener? They wanted to work with root elements!",
  "Why don't web developers like to go shopping? They prefer online stores!",
  "Why did the developer go broke? They lost their keys!",
  "Why don't programmers like to go fishing? They don't like to catch bugs!",
  "Why did the web developer become a detective? They wanted to uncover hidden bugs!",
  "Why don't programmers like to eat alone? They prefer to dine in groups of bytes!",
  "Why did the developer go broke? They didn't get enough interfaces!",
  "Why don't web developers like cupcakes? They prefer cookies!",
  "Why did the developer become a beekeeper? They wanted to use a lot of buzzwords!",
  "Why do programmers prefer the beach? It has great CSS!",
  "Why did the web developer go broke? They lost their domain name in a bet!",
  "Why don't programmers like analog clocks? They prefer digital interfaces!",
  "Why did the developer go broke? They didn't get enough classes!",
  "Why don't web developers like to play cards? They always get confused between clubs and clubs!",
  "Why did the JavaScript developer go broke? They lost their closure!",
  "Why don't programmers like going outside? The WiFi signal is too weak!",
  "Why did the web developer go broke? They couldn't make enough cents!",
  "Why do programmers prefer the desert? It has great sand-boxing!",
  "Why did the web developer refuse to play cards? They didn't know how to handle shuffling!",
  "Why don't web developers get invited to parties? They always break the link!",
  "Why do web developers prefer tea over coffee? Because it's easier to JavaScript!",
  "Why did the web developer become a musician? They wanted to compose web symphonies!",
  "Why don't programmers like to exercise? They prefer software curls!",
  "Why did the web developer always carry a pencil and paper? They liked sketching websites!",
  "Why do programmers prefer dark chocolate? Because it's object-oriented!",
  "Why did the web developer go broke? They lost their cache!",
  "Why did the web developer become a gardener? They wanted to work with root vegetables!",
  "Why don't programmers like HTML? It has too many tags!",
  "Why did the JavaScript developer go broke? Because they lost all their prototypes!",
  "Why don't web developers like to play hide-and-seek? Because they prefer finding elements by class name!",
  "Why did the developer go broke? Their code didn't have enough inheritance!",
  "Why don't programmers like the outdoors? It has too many bugs!",
  "Why did the web developer go broke? They spent all their money on domain names!",
  "Why did the JavaScript developer go broke? Because they lost their scope!",
  "Why don't web developers like to go shopping? They prefer online carts!",
  "Why did the developer get kicked out of school? They couldn't solve their class problems!",
  "Why do programmers prefer seafood? Because they like to catch shell bugs!",
  "Why did the web developer become a detective? They wanted to uncover hidden CSS!",
  "Why don't programmers like to take breaks? They don't want to end up in an infinite loop!",
  "Why did the web developer start a band? They wanted to code in C Major!",
  "Why did the web developer bring a ladder to the bar? They heard the drinks were on the house!",
  "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25!",
  "Why did the JavaScript developer go broke? They lost all their inheritance!",
  "Why don't web developers need umbrellas? They prefer to use cloud services!",
  "Why did the developer go broke? They didn't get enough interfaces!",
  "Why don't programmers like to play hide-and-seek? Because they prefer to use display: none!",
  "Why did the web developer become a zookeeper? They wanted to work with web spiders!",
  "Why don't programmers like to eat alone? Because they prefer to dine in groups of bytes!",
  "Why did the developer go broke? They lost their keys!",
  "Why don't programmers like shopping malls? They prefer the online shopping cart!",
  "Why did the web developer go broke? They spent all their money on hosting fees!",
  "Why don't web developers like cupcakes? They prefer cookies!",
  "Why did the developer become a beekeeper? They wanted to use a lot of buzzwords!",
  "Why do programmers prefer the beach? It has great CSS!",
  "Why did the web developer go broke? They lost their domain name in a bet!",
  "Why don't programmers like analog clocks? They prefer digital interfaces!",
  "Why did the developer go broke? They didn't get enough classes!",
  "Why don't web developers like to play cards? They always get confused between clubs and clubs!",
  "Why did the JavaScript developer go broke? They lost their closure!",
  "Why don't programmers like going outside? The WiFi signal is too weak!",
  "Why did the web developer go broke? They couldn't make enough cents!",
  "Why did the developer get kicked out of school? They couldn't solve their class problems!",
  "Why do programmers prefer dark chocolate? Because it's semisweet!",
  "Why did the web developer become a gardener? They wanted to work with root elements!",
  "Why don't web developers like to go shopping? They prefer online stores!",
  "Why did the developer go broke? Theylost their keys!",
];

const randomProgrammingJoke = () => {
  let randomIndex = Math.floor(Math.random() * programmingJokes.length);
  const jokeGoesHere = document.getElementById("jokeGoesHere");
  jokeGoesHere.innerHTML = `<span style="color: red; font-size:larger;">" </span>${programmingJokes[randomIndex]}<span style="color: red; font-size:larger;"> "</span>`;
};

